#!/bin/sh

### BEGIN INIT INFO
# Provides:          postgres
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: postgres service
# Description:       Run Postgresql service
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Postgres..."
    /bin/sh -c '/usr/local/bin/_postgres.sh postgres' &
    ;;
  stop)
    echo "Stopping Postgres..."
    gosu postgres bash -c 'pg_ctl stop'
    sleep 2
    ;;
  *)
    echo "Usage: /etc/init.d/postgres {start|stop}"
    exit 1
    ;;
esac

exit 0